apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-biblioteca
  labels:
    app: api-biblioteca
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-biblioteca
  template:
    metadata:
      labels:
        app: api-biblioteca
    spec:
      containers:
        - name: api-biblioteca
          image: 
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
